# Generated by Django 4.1.4 on 2023-01-05 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookReferenceId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('BookTitle', models.CharField(max_length=50)),
                ('PageCount', models.IntegerField(default=0)),
                ('Description', models.TextField(null=True)),
                ('Author', models.CharField(max_length=30, null=True)),
                ('ImageUrl', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewComment', models.TextField()),
                ('book_ref', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
