# Generated by Django 4.1.4 on 2023-01-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_review_book_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book_id',
        ),
    ]
