# Generated by Django 4.1.4 on 2023-01-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_book_id_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
    ]
